#!/bin/bash
# 
# Uninstallation script for Hassbian suite: Template
#

function remove {
  echo "
  Removal script does not exist for this suite.
  Please remove manually."
  return 0
}

[[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"