#!/bin/bash
# 
# Upgrade script for Hassbian suite: Template
#

function remove {
  echo "  Upgrade script does not exist for this suite."
  return 0
}

[[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"