#!/bin/bash
# 
# Installation script for Hassbian suite: MySQL
#

function install {
  hassbian.suite.helper.install.apt default-libmysqlclient-dev libssl-dev
  hassbian.suite.helper.install.pip mysqlclient

  echo "Checking the installation..."
  validation=$(sudo -u homeassistant -H /bin/bash << EOF | grep Version | awk '{print $2}'
  source /srv/homeassistant/bin/activate
  python -m pip show mysqlclient
EOF
  )
  if [ ! -z "${validation}" ]; then
    hassbian.suite.helper.action.success
    echo "No database or database user is created during this setup and will need to be created manually."
    echo "To continue have a look at https://home-assistant.io/components/recorder/"
  else
    hassbian.suite.helper.action.failed
    return 1
  fi
  return 0
}

[[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"