#!/bin/bash
# 
# Installation script for Hassbian suite: Hassbian manager
#

function install {
  local ipaddress
  local validation
  local username
  local password

  if [ "$HASSBIAN_RUNTIME_ACCEPT" = true ]; then
    username='pi'
    password='raspberry'
  else
    hassbian.input.info "Please take the time to setup your account"
    username=$(hassbian.input.text "Username:")
    password=$(hassbian.input.text "Password:")
    if [ "$username" == "0" ]; then
      username='pi'
    fi
    if [ "$password" == "0" ]; then
      password='raspberry'
    fi
  fi

  echo "Installing latest version of Hassbian manager..."
  hassbian.suite.helper.install.pip pyhassbian

  echo "Enabling Hassbian manager service..."
  cp /opt/hassbian/suites/manager/files/hassbian-manager@homeassistant.service /etc/systemd/system/hassbian-manager@homeassistant.service

  sed -i "s,%%USERNAME%%,${username},g" /etc/systemd/system/hassbian-manager@homeassistant.service
  sed -i "s,%%PASSWORD%%,${password},g" /etc/systemd/system/hassbian-manager@homeassistant.service

  systemctl enable hassbian-manager@homeassistant.service
  sync

  echo "Starting Hassbian manager..."
  systemctl start hassbian-manager@homeassistant.service

  validation=$(hassbian.suite.verify.service hassbian-manager@homeassistant.service)
  if [ "$validation" == "0" ]; then
    ipaddress=$(hassbian.info.general.ipaddress)
    hassbian.suite.helper.action.success
    echo "Hassbian manager installation is running at http://$ipaddress:9999 or if preferred http://hassbian.local:9999"
  else
    hassbian.suite.helper.action.failed
    return 1
  fi
  return 0
}

[[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"