#!/bin/bash
# 
# Upgrade script for Hassbian suite: Hassbian manager
#

function upgrade {
  echo "UpgradingHassbian manager"
  python3 -m pip install --upgrade pyhassbian

  echo "Restarting Hassbian manager"
  systemctl restart hassbian-manager@homeassistant.service

  validation=$(hassbian.suite.verify.service hassbian-manager@homeassistant.service)
  if [ "$validation" == "0" ]; then
    echo "Upgrade done..."
  else
    echo "Upgrade failed..."
    return 1
  fi
  return 0
}

[[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"