#!/bin/bash
# 
# Upgrade script for Hassbian suite: Custom component store
#

function upgrade {
  echo "Upgrading Custom component store"
  python3 -m pip install --upgrade componentstore

  echo "Restarting Custom component store"
  systemctl restart custom-component-store@homeassistant.service

  validation=$(hassbian.suite.verify.service custom-component-store@homeassistant.service)
  if [ "$validation" == "0" ]; then
    echo "Upgrade done..."
  else
    echo "Upgrade failed..."
    return 1
  fi
  return 0
}

[[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"