#!/bin/bash
# 
# Upgrade script for Hassbian suite: Template
#

function upgrade {
  echo "Upgrading Suite Template..."

  echo "Restarting Template service..."
  systemctl restart custom-component-store@homeassistant.service

  validation=$(hassbian.suite.verify.service template.service)
  if [ "$validation" == "0" ]; then
    hassbian.suite.helper.action.success
  else
    hassbian.suite.helper.action.failed
    return 1
  fi
  return 0
}

[[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"