#!bin/bash
#  Helper script for hassbian-config.
#  Here we store global variables.

# shellcheck disable=SC2034

#####################################
#  Locations
#####################################

# Loggfile for 'hassbian-config' operations.
readonly HASSBIAN_LOG_FILE='/tmp/hassbian.log'

# Suite directory for 'hassbian-config'.
readonly HASSBIAN_SUITE_DIR='/opt/hassbian/suites'

# Controll directory for 'hassbian-config'.
readonly HASSBIAN_CONTROL_DIR='/srv/homeassistant/hassbian/control'

# Home Assistant venv directory.
readonly HOME_ASSISTANT_VENV='/srv/homeassistant'


#####################################
#  Runtime flags
#####################################

# Enabled by adding the --accept flag.
declare HASSBIAN_RUNTIME_ACCEPT=false

# Enabled by adding the --debug flag.
declare HASSBIAN_RUNTIME_DEBUG=false

# Enabled by adding the --force flag.
declare HASSBIAN_RUNTIME_FORCE=false

# Enabled by adding the --force flag.
declare HASSBIAN_RUNTIME_BETA=false

# Enabled by adding the --force flag.
declare HASSBIAN_RUNTIME_DEV=false


#####################################
#  Echoable messages
#####################################

# Warn users about running helper scripts directly.
readonly ECHO_HELPER_WARNING="hassbian-config helper script. Do not run directly, use 'hassbian-config' instead."

[[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"