#!/bin/bash
# 
# Installation script for Hassbian suite: MS SQL
#

function install {
  hassbian.suite.helper.install.apt freetds-dev
  hassbian.suite.helper.install.pip Cython
  hassbian.suite.helper.install.pip pymssql

  echo "Checking the installation..."
  validation=$(sudo -u homeassistant -H /bin/bash << EOF | grep Version | awk '{print $2}'
  source /srv/homeassistant/bin/activate
  python -m pip show pymssql
  EOF
  )
  if [ ! -z "${validation}" ]; then
    echo
    echo -e "\\e[32mInstallation done..\\e[0m"
    echo
    echo "No database or database user is created during this setup and will need to be created manually."
    echo
    echo "To continue have a look at https://home-assistant.io/components/recorder/"
    echo
  else
    echo
    echo -e "\\e[31mInstallation failed..."
    echo
    return 1
  fi
  return 0
}

[[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"