alias halog='sudo journalctl -f -u home-assistant@homeassistant.service'
alias harestart='sudo systemctl restart home-assistant@homeassistant.service'
alias hashell='sudo su -s /bin/bash homeassistant'
alias hastart='sudo systemctl start home-assistant@homeassistant.service'
alias hastatus='sudo systemctl status home-assistant@homeassistant.service'
alias hastop='sudo systemctl stop home-assistant@homeassistant.service'