#!/bin/bash
# 
# Installation script for Hassbian suite: Web Terminal
#

function install {
  local certdir
  local domain
  local protocol
  local usingssl
  local validation
  local ipaddress

  if [ "$ACCEPT" == "true" ]; then # True if `-y` flag is used.
    if [ -d "/etc/letsencrypt/live" ] || [ -d "/home/homeassistant/dehydrated/certs" ]; then
      usingssl="0"
    fi
  else
    usingssl=$(hassbian.input.bool "Do you use SSL (https) with Home Assistant?")
  fi

  echo "Installing packages."
  hassbian.suite.helper.install.apt shellinabox

  echo "Changing config."
  if [ "$usingssl" == "0" ]; then
    echo "No need to change default configuration, skipping this step..."
    echo "Checking certificate directories..."
    if [ -d "/etc/letsencrypt/live" ]; then
      certdir="/etc/letsencrypt/live/"
    elif [ -d "/home/homeassistant/dehydrated/certs" ]; then
      certdir="/home/homeassistant/dehydrated/certs/"
    else
      echo "Could not find a valid cerification directory..."
      hassbian.suite.helper.action.failed
      return 1
    fi
    echo "Merging files and adding to correct dir..."
    domain=$(ls "$certdir")
    cat "$certdir$domain/fullchain.pem" "$certdir$domain/privkey.pem" > /var/lib/shellinabox/certificate-"$domain".pem
    chown shellinabox:shellinabox -R /var/lib/shellinabox/
    echo "Adding crong job to copy certs..."
    cp HASSBIAN_SUITE_DIR/webterminal/files/cron /etc/cron.daily/shellinabox
  else
    sed -i 's/--no-beep/--no-beep --disable-ssl/g' /etc/default/shellinabox
  fi

  echo "Reloading and starting the service."
  service shellinabox reload
  service shellinabox stop
  service shellinabox start

  if [ "$usingssl" == "0" ]; then
    protocol="https"
  else
    protocol="http"
  fi

  echo "Checking the installation..."
  validation=$(hassbian.suite.verify.pgrep shellinaboxd)
  if [ "$validation" == "0" ]; then
    ipaddress=$(hassbian.info.general.ipaddress)
    hassbian.suite.helper.action.success
    echo "You can now access the web terminal here: $protocol://$ipaddress:4200"
    echo "You can also add this to your Home-Assistant config in an 'panel_iframe'"
  else
    hassbian.suite.helper.action.failed
    return 1
  fi
  return 0
}

[[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"