#!/bin/bash
# 
# Installation script for Hassbian suite: AppDaemon
#

function install {
  local activatesamba
  local homeassistant_password
  local python_version

  if [ "$HASSBIAN_RUNTIME_ACCEPT" = false ]; then
    if [ -f "/usr/sbin/samba" ]; then
      activatesamba=$(hassbian.input.bool "Do you want to add Samba share for AppDaemon configuration?")
    fi
    homeassistant_password=$(hassbian.input.text "Enter your Home Assistant API password:")
  else
    homeassistant_password=""
  fi

  echo "Checking python version to use..."
  python_version=$(hassbian.info.version.python)
  echo "Using python$python_version..."

  echo "Creating directory for AppDaemon Venv"
  mkdir /srv/appdaemon
  chown -R homeassistant:homeassistant /srv/appdaemon

  echo "Changing to the homeassistant user..."
  sudo -u homeassistant -H /bin/bash << EOF
    echo "Creating AppDaemon venv..."
    python"$python_version" -m venv /srv/appdaemon

    echo "Changing to AppDaemon venv..."
    source /srv/appdaemon/bin/activate

    echo "Creating directory for AppDaemon configuration file..."
    mkdir /home/homeassistant/appdaemon
    mkdir /home/homeassistant/appdaemon/apps

    echo "Installing latest version of AppDaemon..."
    python -m pip install setuptools wheel
    python -m pip install appdaemon

    source "$HASSBIAN_HELPERS_DIR"/workaround
    hassbian.workaround.check appdaemon

    echo "Copying AppDaemon config file..."
    cp $HASSBIAN_SUITE_DIR/appdaemon/files/appdaemon.conf /home/homeassistant/appdaemon/appdaemon.yaml
    if [ ! -z "${HOMEASSISTANT_PASSWORD}" ]; then
        sed -i 's/#ha_key:/ha_key: $HOMEASSISTANT_PASSWORD/g' /home/homeassistant/appdaemon/appdaemon.yaml
    fi

    echo "Deactivating virtualenv..."
    deactivate
EOF

  echo "Copying AppDaemon service file"
  cp "$HASSBIAN_SUITE_DIR"/appdaemon/files/appdaemon.service /etc/systemd/system/appdaemon@homeassistant.service

  echo "Enabling AppDaemon service"
  systemctl enable appdaemon@homeassistant.service
  sync

  echo "Starting AppDaemon service"
  systemctl start appdaemon@homeassistant.service

  if [ "$activatesamba" == "0" ]; then
    echo "Adding configuration to Samba..."
    tee -a /etc/samba/smb.conf < "$HASSBIAN_SUITE_DIR"/appdaemon/files/samba.conf

    echo "Restarting Samba service"
    systemctl restart smbd.service
  fi

  validation=$(hassbian.suite.verify.service appdaemon@homeassistant.service)
  if [ "$validation" == "0" ]; then
    hassbian.suite.helper.action.success

    echo "You will find the AppDaemon configuration files in:
    /home/homeassistant/appdaemon

    To continue have a look at http://appdaemon.readthedocs.io/en/latest/"
  else
    hassbian.suite.helper.action.failed
    return 1
  fi
  return 0
}

[[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"