#!bin/bash
#  Helper script for hassbian-config.

# shellcheck disable=SC1090

declare suitename
declare suitestate
declare suiteaction
declare retrunedvalue

function hassbian.suite.action {
  # Purpose: Check if a suite exist.
  # Return 0 if found, else 1.

  suiteaction="$1"
  suitename="$2"

  # Root check.
  hassbian.info.general.rootcheck

  # Verify that the suite exist.
  hassbian.suite.helper.exist "$suitename"

  # Show info
  if [ "$suiteaction" == "show" ]; then
    hassbian.suite.info.print "$suitename"
    exit
  fi

  # Generate systeminfo
  hassbian.info.general.systeminfo

  # Echo metadata
  hassbian.suite.info.print "$suitename"

  # Do checks to see if the suite can be run.
  hassbian.suite.helper.blockcheck "$suitename"
  hassbian.suite.helper.pizerocheck "$suitename"

  # Activate debug
  if [ "$HASSBIAN_RUNTIME_DEBUG" = true ]; then set -x; fi

  # Run the suite action.
  if [[ "$suiteaction" =~ ^(install|upgrade|remove)$ ]]; then
    if [ -f "$HASSBIAN_SUITE_DIR/$suitename/$suiteaction" ]; then
      source "$HASSBIAN_SUITE_DIR/$suitename/$suiteaction"
      "$suiteaction" | tee "$HASSBIAN_LOG_FILE"
      returnvalue="$?"

      return "$returnvalue"
    else
      echo "$suiteaction script does not exist for this suite."
    fi
  else
    echo "$suiteaction is not a valid suite action."
    exit 1
  fi

  # Deactivate debug
  if [ "$HASSBIAN_RUNTIME_DEBUG" == true ]; then set +x; fi

  # Post action
  if [ "$retrunedvalue" == "0" ]; then
    suitestate="installed"
  else
    echo "$ECHO_ACTION_ERROR"
    suitestate="failed"
  fi

  if [ "$suiteaction" == "remove" ]; then 
    rm "$HASSBIAN_CONTROL_DIR/$suitename"
  else
    echo "SCRIPTSTATE=$suitestate" > "$HASSBIAN_CONTROL_DIR/$suitename"
  fi
}

[[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"