#!bin/bash
#  Helper script for hassbian-config.

declare suitename

function hassbian.suite.exist {
  # Purpose: Check if a suite exist.

  suitename="$1"

  # Check if suite name is empty.
  if [ -z "$suitename" ]; then
    echo "Suitename cannot be empty."
    exit 1
  fi

  # Check if suite directory exist.
  if [ ! -d "$HASSBIAN_SUITE_DIR/$1" ]; then
    echo "$suitename does not exist."
    exit 1
  else

    # Check if suite manifest file exist.
    if [ ! -f "$HASSBIAN_SUITE_DIR/$1/manifest" ]; then
      echo "$suitename are missing manifest file."
      exit 1
    fi

    # Check if suite install file exist.
    if [ ! -f "$HASSBIAN_SUITE_DIR/$1/install" ]; then
      echo "$suitename are missing install file."
      exit 1
    fi

    # Check if suite upgrade file exist.
    if [ ! -f "$HASSBIAN_SUITE_DIR/$1/upgrade" ]; then
      echo "$suitename are missing upgrade file."
      exit 1
    fi

    # Check if suite remove file exist.
    if [ ! -f "$HASSBIAN_SUITE_DIR/$1/remove" ]; then
      echo "$suitename are missing remove file."
      exit 1
    fi
  fi

  exit 0
}

[[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"