#!bin/bash
#  Helper script for hassbian-config.

declare packages
declare suitename
declare manifestkey

function hassbian.suite.helper.install.pip {
  # Purpose: Install python packages in the homeassistant venv.
  # Usage:
  # hassbian.suite.helper.install.pip sampleclient
  # hassbian.suite.helper.install.pip sampleclient someotherpackage
  packages="$1"

  echo "Changing to homeassistant user..."
  sudo -u homeassistant -H /bin/bash << EOF

  echo "Changing to Home Assistant venv..."
  source /srv/homeassistant/bin/activate

  echo "Updating Python dependencies..."
  python -m pip install --upgrade setuptools wheel"

  echo "Installing Python packages..."
  python -m pip install "$packages"

  echo "Deactivating virtualenv..."
  deactivate
EOF
}

function hassbian.suite.helper.install.apt {
  # Purpose: Install apt packages.
  # Usage:
  # hassbian.suite.helper.install.apt sampleclient
  # hassbian.suite.helper.install.apt sampleclient someotherpackage
  packages="$1"

  echo "Updating apt..."
  apt update

  echo "Installing packages..."
  apt install -y "$packages"
}

function hassbian.suite.helper.manifest {
  # Purpose: retrun info from the suite manifest.
  # Usage:
  # hassbian.suite.helper.manifest [suite] [key]
  # hassbian.suite.helper.manifest duckdns author
  local manifestvalue

  suitename="$1"
  manifestkey="$2"

  manifestvalue=$(jq ."$manifestkey" -r "$HASSBIAN_SUITE_DIR"/"$suitename"/manifest)
  printf "%s" "$manifestvalue"
}

[[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"