#!bin/bash
#  Helper script for hassbian-config.

declare suitename

function hassbian.suite.info.print {
  # Show information about a suite.
  # Usage example:
  # hassbian.suite.info.print [suite]
  # hassbian.suite.info.print duckdns
  local author
  local name
  local long_description
  local isinstalled
  local installed

  suitename="$1"

  author=$(hassbian.suite.helper.manifest "$suitename" author)
  name=$(hassbian.suite.helper.manifest "$suitename" name)
  long_description=$(hassbian.suite.helper.manifest "$suitename" long_description)
  isinstalled=$(hassbian.suite.info.installed "$suitename")

  if [ "$isinstalled" ]; then
    installed='True'
  else
    installed='False'
  fi

  echo -e "
Suite:     $name
Installed: $installed
Contributed to the project by $author
$long_description
"
}

function hassbian.suite.info.installed {
  # Return 0 if installed, else 1.
  # Usage example:
  # hassbian.suite.info.installed [suite]
  # hassbian.suite.info.installed duckdns
  local isinstalled
  local suitestate

  suitename="$1"
  isinstalled=1

  if [ -f "$HASSBIAN_CONTROL_DIR"/"$suitename" ]; then
    suitestate=$(grep "SCRIPTSTATE" "$HASSBIAN_CONTROL_DIR"/"$suitename" | \
      awk -F'=' '{print $2}')
      if [ "$suitestate" == "isntalled" ]; then
        isinstalled=0
      fi
  fi
  return "$isinstalled"
}

[[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"