#!bin/bash
#  Helper script for hassbian-config.

# shellcheck disable=SC1090

declare suitename

function hassbian.suite.install {
  # Purpose: Install a suite.
  local returnvalue

  suitename="$1"

  if [ -f "$HASSBIAN_SUITE_DIR/$suitename/install" ]; then
    source "$HASSBIAN_SUITE_DIR/$suitename/install"
    install
    returnvalue="$?"

    return "$returnvalue"
  else
    echo "$ECHO_MISSING_INSTALL"
  fi
}

[[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"