#!bin/bash
#  Helper script for hassbian-config.

declare suitename

function hassbian.suite.remove {
  # Purpose: Remove a suite.

  suitename="$1"

}

[[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"