#!bin/bash
#  Helper script for hassbian-config.

# shellcheck disable=SC1090

declare suitename

function hassbian.suite.upgrade {
  # Purpose: Upgrade a suite.
  local returnvalue

  suitename="$1"
  if [ -f "$HASSBIAN_SUITE_DIR/$suitename/upgrade" ]; then
    source "$HASSBIAN_SUITE_DIR/$suitename/upgrade"
    returnvalue=$(upgrade)

    return "$returnvalue"
  else
    echo "$ECHO_MISSING_UPGRADE"
  fi
}

[[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"